name: Deploy Infrastructure & Configure Server

on:
  push:
    branches:
    - main

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      working-directory: ./terraform
      run: terraform init

    - name: Terraform Apply
      working-directory: ./terraform
      run: terraform apply -auto-approve

  ansible:
    name: Run Ansible
    runs-on: ubuntu-latest
    needs: terraform

    env:
      ANSIBLE_HOST_KEY_CHECKING: "False"

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Get EC2 IP from Terraform
      working-directory: ./terraform
      run: |
        terraform output -raw instance_ip > ../ansible/host_ip.txt

    - name: Create Ansible inventory
      run: |
        IP=$(cat ansible/host_ip.txt)
        echo "[monitoring]" > ansible/hosts
        echo "$IP ansible_user=ubuntu ansible_ssh_private_key_file=ansible/key.pem" >> ansible/hosts

    - name: Setup private SSH key
      run: |
        mkdir -p ansible
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ansible/key.pem
        chmod 400 ansible/key.pem

    - name: Install Ansible
      run: sudo apt-get update && sudo apt-get install -y ansible

    - name: Run Ansible playbook
      working-directory: ./ansible
      run: ansible-playbook -i hosts playbook.yml

